import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Bell,
  CheckCircle,
  AlertTriangle,
  Flame,
  Globe,
  Clock,
  ArrowRight,
  ExternalLink,
  Filter,
  RefreshCw
} from 'lucide-react';
import { api } from '../services/api';
import { AlertRecord } from '../types';
import { RiskBadge } from '../components/common/RiskBadge';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [filterSeverity, setFilterSeverity] = useState('');
  const navigate = useNavigate();

  const loadAlerts = async () => {
    setLoading(true);
    try {
      const data = await api.getAlerts();
      setAlerts(data);
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const handleAcknowledge = async (id: string) => {
    try {
      await api.acknowledgeAlert(id);
      setAlerts(prev => prev.map(a => (a.id === id ? { ...a, acknowledged: true } : a)));
    } catch (err) {
      console.error('Failed to acknowledge alert:', err);
    }
  };

  const filtered = alerts.filter(a => (filterSeverity ? a.severity === filterSeverity : true));

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto" id="alerts-container">
      {/* Header */}
      <div className="border-b border-slate-800 pb-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-mono text-cyan-400 font-semibold tracking-wider uppercase">
            Surveillance Tripwires
          </span>
          <h1 className="text-2xl font-bold text-white tracking-tight mt-0.5">
            Real-Time Threat Alerts & Anomaly Feed
          </h1>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Automated alerts generated by on-chain heuristic triggers and high-velocity fund movements
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <select
            value={filterSeverity}
            onChange={e => setFilterSeverity(e.target.value)}
            className="px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-950 text-xs font-mono text-slate-300 focus:outline-none cursor-pointer"
          >
            <option value="">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
          </select>

          <button
            onClick={loadAlerts}
            className="p-2 rounded-lg border border-slate-800 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Alerts Stream List */}
      <div className="space-y-3 font-mono text-xs">
        {filtered.map(alert => (
          <div
            key={alert.id}
            className={`p-4 rounded-xl border transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 ${
              alert.acknowledged
                ? 'border-slate-800/60 bg-[#090e1a]/40 opacity-70'
                : 'border-slate-800 bg-[#090e1a]/90 shadow-md hover:border-slate-700'
            }`}
          >
            <div className="flex items-start space-x-3">
              <div className={`p-2 rounded-lg shrink-0 ${
                alert.severity === 'CRITICAL'
                  ? 'bg-red-950/60 border border-red-800 text-red-400'
                  : 'bg-amber-950/60 border border-amber-800 text-amber-400'
              }`}>
                <Bell className="w-5 h-5" />
              </div>

              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <h3 className="font-bold text-white text-sm">
                    {alert.title}
                  </h3>
                  <RiskBadge category={alert.severity} size="sm" />
                </div>
                <p className="text-slate-300 text-xs leading-relaxed">
                  {alert.description}
                </p>
                <div className="flex flex-wrap items-center gap-3 text-[10px] text-slate-400 pt-1">
                  <span>Target: <span className="text-cyan-400">{alert.walletAddress}</span></span>
                  <span>•</span>
                  <span>{new Date(alert.timestamp).toLocaleString()}</span>
                  {alert.acknowledged && (
                    <>
                      <span>•</span>
                      <span className="text-emerald-400">Acknowledged</span>
                    </>
                  )}
                </div>
              </div>
            </div>

            <div className="flex items-center space-x-2 self-end md:self-center shrink-0">
              {!alert.acknowledged && (
                <button
                  onClick={() => handleAcknowledge(alert.id)}
                  className="px-3 py-1.5 rounded-lg border border-slate-700 hover:bg-slate-800 text-slate-300 text-xs transition-all"
                >
                  Acknowledge
                </button>
              )}
              <button
                onClick={() => navigate(`/investigations?wallet=${encodeURIComponent(alert.walletAddress)}`)}
                className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold text-xs tracking-wider transition-all"
              >
                Investigate
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
